language: elixir
elixir:
  - "1.4.1"
otp_release:
  - "18.0"
sudo: false
before_script:
  - nvm install 6.2 && nvm use 6.2
  - bin/setup-ci
script: "mix test"
cache:
  directories:
  - "deps"
notifications:
  email: false
